name: Auto Apply Migrations

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Preview' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Apply migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
        run: npx prisma migrate deploy

      - name: Seed database
        if: github.ref == 'refs/heads/dev'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
          NODE_ENV: development
        run: npm run prisma:seed
